### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by doofin** [Trundle/idris-go#2]
stack build 

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for idris-1.3.0(+FFI +GMP):
    fingertree-0.1.3.1 from stack configuration does not match >=0.1.4.1 && <0.2  (latest matching version is 0.1.4.1)
needed due to idris-go-0.0.0.1 -> idris-1.3.0

Some different approaches to resolving this:

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build
    configuration. This can be convenient when dealing with many complicated constraint errors, but results may be
    unpredictable.

  * Recommended action: try adding the following to your extra-deps in /media/mass0/work/idris-go/stack.yaml:

- fingertree-0.1.4.1

Plan construction failed.

**Comment by Trundle** [comment]
Thank you for the report. I switched to LTS Haskell in commit 9510b7b41b7fec03ca8d71f7f6b160e259da829c and idris-go should build again.
